/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopkeeperRouteImport } from './routes/shopkeeper'
import { Route as IndexRouteImport } from './routes/index'

const ShopkeeperRoute = ShopkeeperRouteImport.update({
  id: '/shopkeeper',
  path: '/shopkeeper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shopkeeper': typeof ShopkeeperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shopkeeper': typeof ShopkeeperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shopkeeper': typeof ShopkeeperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shopkeeper'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shopkeeper'
  id: '__root__' | '/' | '/shopkeeper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopkeeperRoute: typeof ShopkeeperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopkeeper': {
      id: '/shopkeeper'
      path: '/shopkeeper'
      fullPath: '/shopkeeper'
      preLoaderRoute: typeof ShopkeeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopkeeperRoute: ShopkeeperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
